#!/usr/bin/env python3
"""Generate conservative Make dependencies for Fortran module users.

The project makefile compiles sources in a fixed order, which is enough for a
clean build. Incremental builds also need consumers to rebuild when a module
provider changes; otherwise old objects can link against a newer `.mod` ABI.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


MODULE_RE = re.compile(r"^\s*module\s+(?!procedure\b)([a-z_]\w*)\b", re.IGNORECASE)
USE_RE = re.compile(
    r"^\s*use\s*(?:,\s*(intrinsic|non_intrinsic)\s*)?(?:::)?\s*([a-z_]\w*)\b",
    re.IGNORECASE,
)
SOURCE_SUFFIXES = {".f90", ".F90"}
INTRINSIC_MODULES = {
    "ieee_arithmetic",
    "iso_c_binding",
    "iso_fortran_env",
}


def strip_comment(line: str) -> str:
    return line.split("!", 1)[0]


def logical_lines(path: Path) -> list[str]:
    result: list[str] = []
    pending = ""
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = strip_comment(raw_line).rstrip()
        continued = line.endswith("&")
        if continued:
            line = line[:-1].rstrip()
        if pending:
            line = pending + " " + line.lstrip("&").lstrip()
        if continued:
            pending = line
            continue
        if line.strip():
            result.append(line)
        pending = ""
    if pending.strip():
        result.append(pending)
    return result


def object_path(root: Path, obj_dir: str, source: Path) -> str:
    rel = source.relative_to(root).with_suffix(".o")
    return str(Path(obj_dir) / rel)


def discover_sources(root: Path) -> list[Path]:
    sources: list[Path] = []
    for dirname in ("src", "tests"):
        base = root / dirname
        if not base.exists():
            continue
        sources.extend(path for path in base.rglob("*") if path.suffix in SOURCE_SUFFIXES)
    return sorted(sources)


def parse_source(path: Path) -> tuple[set[str], set[str]]:
    provides: set[str] = set()
    uses: set[str] = set()
    for line in logical_lines(path):
        module_match = MODULE_RE.match(line)
        if module_match:
            provides.add(module_match.group(1).lower())
            continue
        use_match = USE_RE.match(line)
        if not use_match:
            continue
        intrinsic_kind = (use_match.group(1) or "").lower()
        module_name = use_match.group(2).lower()
        if intrinsic_kind == "intrinsic" or module_name in INTRINSIC_MODULES:
            continue
        uses.add(module_name)
    return provides, uses


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default="..", help="repository root relative to the make working directory")
    parser.add_argument("--obj-dir", default=".obj", help="object directory relative to the make working directory")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    sources = discover_sources(root)
    source_info = {source: parse_source(source) for source in sources}

    module_provider: dict[str, Path] = {}
    for source, (provides, _uses) in source_info.items():
        for module_name in provides:
            module_provider[module_name] = source

    print("# Generated by scripts/fortran_module_deps.py; do not edit.")
    for source in sources:
        source_obj = object_path(root, args.obj_dir, source)
        _provides, uses = source_info[source]
        deps: list[str] = []
        for module_name in sorted(uses):
            provider = module_provider.get(module_name)
            if provider is None or provider == source:
                continue
            deps.append(object_path(root, args.obj_dir, provider))
        if deps:
            print(f"{source_obj}: {' '.join(dict.fromkeys(deps))}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
